apiVersion: v1
kind: Service
metadata:
  name: portal-gateway-svc
spec:
  type: NodePort
  selector:
    app: portal-gateway
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-gateway
  template:
    metadata:
      labels:
        app: portal-gateway
    spec:
      containers:
      - name: portal-gateway
        image: nsx-docker.artifactory.nortal.com/portal-gateway:24
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
